# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20180821_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='gname',
        ),
        migrations.AlterField(
            model_name='group',
            name='gid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
